import type { SalesEvent } from "./types";

function relDate(daysFromNow: number): string {
  return new Date(Date.now() + daysFromNow * 86400000).toISOString();
}

export const mockEvents: SalesEvent[] = [
  {
    id: "evt-modex-2026",
    name: "MODEX 2026",
    date: relDate(18),
    endDate: relDate(21),
    location: "Atlanta, GA",
    type: "tradeshow",
    status: "upcoming",
    description:
      "The premier supply chain tradeshow featuring 1,000+ exhibitors and 45,000+ attendees. Key opportunity to connect with VP-level supply chain leaders in food distribution, furniture, and industrial equipment.",
    website: "https://www.modexshow.com",
    territories: ["Southeast", "Northeast", "West Coast"],
    attendees: [
      {
        id: "att-1",
        firstName: "Marcus",
        lastName: "Rivera",
        company: "US Foods",
        position: "VP of Supply Chain",
        email: "m.rivera@usfoods.com",
        linkedinUrl: "https://linkedin.com/in/marcusrivera",
        territory: "Southeast",
        icpScore: 92,
        tier: "hot",
        outreachStatus: "contacted",
        assignedTo: "Santiago",
        notes: "Met at last year's ProMat. Interested in inventory optimization.",
      },
      {
        id: "att-2",
        firstName: "Linda",
        lastName: "Chen",
        company: "Performance Food Group",
        position: "Director of Procurement",
        email: "l.chen@pfgc.com",
        territory: "Southeast",
        icpScore: 88,
        tier: "hot",
        outreachStatus: "meeting_booked",
        assignedTo: "Santiago",
      },
      {
        id: "att-3",
        firstName: "James",
        lastName: "Worthington",
        company: "HD Supply",
        position: "SVP Operations",
        email: "j.worthington@hdsupply.com",
        territory: "Southeast",
        icpScore: 85,
        tier: "hot",
        outreachStatus: "scheduled",
        assignedTo: "Diego",
      },
      {
        id: "att-4",
        firstName: "Patricia",
        lastName: "Nakamura",
        company: "Ashley Furniture",
        position: "VP Logistics",
        email: "p.nakamura@ashleyfurniture.com",
        territory: "Southeast",
        icpScore: 80,
        tier: "hot",
        outreachStatus: "not_started",
        assignedTo: "Santiago",
      },
      {
        id: "att-5",
        firstName: "Robert",
        lastName: "Adams",
        company: "Sysco Corporation",
        position: "Director of Supply Chain Technology",
        email: "r.adams@sysco.com",
        territory: "Southeast",
        icpScore: 90,
        tier: "hot",
        outreachStatus: "contacted",
        assignedTo: "Diego",
      },
      {
        id: "att-6",
        firstName: "Elena",
        lastName: "Vasquez",
        company: "McKesson",
        position: "VP Procurement",
        email: "e.vasquez@mckesson.com",
        territory: "Northeast",
        icpScore: 87,
        tier: "hot",
        outreachStatus: "meeting_booked",
        assignedTo: "Santiago",
      },
      {
        id: "att-7",
        firstName: "David",
        lastName: "Kim",
        company: "Cardinal Health",
        position: "Director of Operations",
        email: "d.kim@cardinalhealth.com",
        territory: "Northeast",
        icpScore: 78,
        tier: "warm",
        outreachStatus: "scheduled",
        assignedTo: "Diego",
      },
      {
        id: "att-8",
        firstName: "Sarah",
        lastName: "Mitchell",
        company: "Grainger",
        position: "Supply Chain Manager",
        email: "s.mitchell@grainger.com",
        territory: "Northeast",
        icpScore: 72,
        tier: "warm",
        outreachStatus: "not_started",
      },
      {
        id: "att-9",
        firstName: "Thomas",
        lastName: "O'Brien",
        company: "Fastenal",
        position: "VP Distribution",
        email: "t.obrien@fastenal.com",
        territory: "Northeast",
        icpScore: 76,
        tier: "warm",
        outreachStatus: "contacted",
        assignedTo: "Santiago",
      },
      {
        id: "att-10",
        firstName: "Michelle",
        lastName: "Park",
        company: "Genuine Parts Company",
        position: "Director of Procurement",
        email: "m.park@genpt.com",
        territory: "Northeast",
        icpScore: 81,
        tier: "hot",
        outreachStatus: "not_started",
      },
      {
        id: "att-11",
        firstName: "Kevin",
        lastName: "Patel",
        company: "C&S Wholesale Grocers",
        position: "COO",
        email: "k.patel@cswg.com",
        territory: "West Coast",
        icpScore: 95,
        tier: "hot",
        outreachStatus: "meeting_booked",
        assignedTo: "Santiago",
      },
      {
        id: "att-12",
        firstName: "Amanda",
        lastName: "Torres",
        company: "Uline",
        position: "VP Supply Chain",
        email: "a.torres@uline.com",
        territory: "West Coast",
        icpScore: 83,
        tier: "hot",
        outreachStatus: "scheduled",
        assignedTo: "Diego",
      },
      {
        id: "att-13",
        firstName: "Brian",
        lastName: "Foster",
        company: "WESCO International",
        position: "Director of Logistics",
        email: "b.foster@wesco.com",
        territory: "West Coast",
        icpScore: 74,
        tier: "warm",
        outreachStatus: "not_started",
      },
      {
        id: "att-14",
        firstName: "Rachel",
        lastName: "Nguyen",
        company: "Floor & Decor",
        position: "Supply Chain Director",
        email: "r.nguyen@flooranddecor.com",
        territory: "West Coast",
        icpScore: 69,
        tier: "warm",
        outreachStatus: "contacted",
        assignedTo: "Diego",
      },
      {
        id: "att-15",
        firstName: "Daniel",
        lastName: "Rodriguez",
        company: "McLane Company",
        position: "VP Operations",
        email: "d.rodriguez@mclaneco.com",
        territory: "West Coast",
        icpScore: 86,
        tier: "hot",
        outreachStatus: "not_started",
        assignedTo: "Santiago",
      },
    ],
    outreachPlan: {
      id: "plan-modex-2026",
      eventId: "evt-modex-2026",
      preEventSequence: [
        {
          step: 1,
          channel: "email",
          template:
            "Subject: See you at MODEX? | Hi {firstName}, I noticed {company} is attending MODEX 2026. We're helping distributors like yours cut fill rate gaps by 0.25% and free up $2M+ in working capital. Would love 15 min to show you how. Available [date]?",
          timing: "3 weeks before event",
        },
        {
          step: 2,
          channel: "linkedin",
          template:
            "Hey {firstName}, looking forward to MODEX! I saw your talk on {topic} last year - great insights. Would love to connect beforehand and share some data on how AI is transforming procurement for {industry} distributors.",
          timing: "2 weeks before event",
        },
        {
          step: 3,
          channel: "email",
          template:
            "Subject: Quick MODEX agenda check | Hi {firstName}, just confirming - are you free [time slot] at MODEX? I'd love to walk you through how we helped a {industry} distributor reduce emergency POs by 92%. Booth #{boothNumber} or happy to grab coffee nearby.",
          timing: "1 week before event",
        },
      ],
      atEventTasks: [
        "Visit each pre-scheduled meeting at booth or meeting room",
        "Collect badge scans and business cards - log in app immediately",
        "Take notes on pain points discussed within 30 min of each conversation",
        "Send same-day LinkedIn connection request with personal note",
        "Attend keynote sessions to identify additional prospects",
      ],
      postEventSequence: [
        {
          step: 1,
          channel: "email",
          template:
            "Subject: Great meeting at MODEX | Hi {firstName}, it was great connecting at MODEX. As discussed, here's the case study on how we helped [similar company] achieve [specific result]. Would [date] work for a deeper dive?",
          timing: "1 day after event",
        },
        {
          step: 2,
          channel: "linkedin",
          template:
            "Great connecting at MODEX, {firstName}! Enjoyed our conversation about {topic}. Sent over that case study via email - let me know what you think.",
          timing: "2 days after event",
        },
        {
          step: 3,
          channel: "email",
          template:
            "Subject: {company} + Balboa - next steps | Hi {firstName}, following up on our MODEX conversation. I've put together a personalized ROI analysis for {company} based on what you shared. When works for a 20-min walkthrough?",
          timing: "1 week after event",
        },
        {
          step: 4,
          channel: "call",
          template:
            "Call script: Reference MODEX conversation, specific pain point discussed, offer personalized demo. Have ROI calculator ready.",
          timing: "10 days after event",
        },
      ],
      goals: {
        meetingsTarget: 8,
        leadsTarget: 15,
        connectionsTarget: 30,
      },
    },
    teamProgress: {
      totalAttendees: 15,
      contacted: 9,
      meetingsBooked: 3,
      noShows: 0,
      byTerritory: [
        { territory: "Southeast", total: 5, contacted: 4, meetings: 1 },
        { territory: "Northeast", total: 5, contacted: 3, meetings: 1 },
        { territory: "West Coast", total: 5, contacted: 2, meetings: 1 },
      ],
    },
  },
  {
    id: "evt-sci-summit-2026",
    name: "Supply Chain Innovation Summit",
    date: relDate(35),
    endDate: relDate(36),
    location: "Chicago, IL",
    type: "conference",
    status: "upcoming",
    description:
      "Two-day conference focused on AI and automation in supply chain. Panel discussions, fireside chats, and networking with 500+ senior supply chain executives.",
    website: "https://www.scisummit.com",
    territories: ["Midwest", "Northeast"],
    attendees: [
      {
        id: "att-20",
        firstName: "Gregory",
        lastName: "Thompson",
        company: "US Foods",
        position: "Chief Supply Chain Officer",
        email: "g.thompson@usfoods.com",
        territory: "Midwest",
        icpScore: 96,
        tier: "hot",
        outreachStatus: "not_started",
        assignedTo: "Santiago",
      },
      {
        id: "att-21",
        firstName: "Jennifer",
        lastName: "Walsh",
        company: "Kraft Heinz",
        position: "VP Global Procurement",
        email: "j.walsh@kraftheinz.com",
        territory: "Midwest",
        icpScore: 88,
        tier: "hot",
        outreachStatus: "not_started",
      },
      {
        id: "att-22",
        firstName: "Carlos",
        lastName: "Mendez",
        company: "Caterpillar",
        position: "Director Supply Chain Digital Transformation",
        email: "c.mendez@caterpillar.com",
        territory: "Midwest",
        icpScore: 79,
        tier: "warm",
        outreachStatus: "not_started",
        assignedTo: "Diego",
      },
      {
        id: "att-23",
        firstName: "Priya",
        lastName: "Sharma",
        company: "Abbott Laboratories",
        position: "VP Operations",
        email: "p.sharma@abbott.com",
        territory: "Midwest",
        icpScore: 82,
        tier: "hot",
        outreachStatus: "not_started",
      },
      {
        id: "att-24",
        firstName: "William",
        lastName: "Sato",
        company: "Performance Food Group",
        position: "CTO",
        email: "w.sato@pfgc.com",
        territory: "Northeast",
        icpScore: 75,
        tier: "warm",
        outreachStatus: "not_started",
        assignedTo: "Santiago",
      },
      {
        id: "att-25",
        firstName: "Angela",
        lastName: "Cooper",
        company: "Danaher",
        position: "VP Supply Chain Strategy",
        email: "a.cooper@danaher.com",
        territory: "Northeast",
        icpScore: 84,
        tier: "hot",
        outreachStatus: "not_started",
      },
      {
        id: "att-26",
        firstName: "Ryan",
        lastName: "Fitzgerald",
        company: "Arrow Electronics",
        position: "Director of Procurement",
        email: "r.fitzgerald@arrow.com",
        territory: "Northeast",
        icpScore: 77,
        tier: "warm",
        outreachStatus: "not_started",
        assignedTo: "Diego",
      },
      {
        id: "att-27",
        firstName: "Samantha",
        lastName: "Lee",
        company: "Henry Schein",
        position: "SVP Distribution",
        email: "s.lee@henryschein.com",
        territory: "Northeast",
        icpScore: 91,
        tier: "hot",
        outreachStatus: "not_started",
        assignedTo: "Santiago",
      },
    ],
    teamProgress: {
      totalAttendees: 8,
      contacted: 0,
      meetingsBooked: 0,
      noShows: 0,
      byTerritory: [
        { territory: "Midwest", total: 4, contacted: 0, meetings: 0 },
        { territory: "Northeast", total: 4, contacted: 0, meetings: 0 },
      ],
    },
  },
  {
    id: "evt-q1-webinar",
    name: "Q1 Logistics Webinar",
    date: relDate(-10),
    endDate: relDate(-10),
    location: "Virtual",
    type: "webinar",
    status: "completed",
    description:
      "Balboa-hosted webinar on 'Reducing Emergency POs by 92%: How AI Transforms Direct Procurement'. 45-minute presentation followed by 15 minutes of Q&A.",
    territories: ["National"],
    attendees: [
      {
        id: "att-30",
        firstName: "Christine",
        lastName: "Baker",
        company: "Sysco Corporation",
        position: "Supply Chain Manager",
        email: "c.baker@sysco.com",
        territory: "National",
        icpScore: 71,
        tier: "warm",
        outreachStatus: "contacted",
        assignedTo: "Santiago",
        notes: "Asked multiple questions during Q&A about ERP integration.",
      },
      {
        id: "att-31",
        firstName: "Mark",
        lastName: "Henderson",
        company: "Uline",
        position: "Director of Inventory Planning",
        email: "m.henderson@uline.com",
        territory: "National",
        icpScore: 80,
        tier: "hot",
        outreachStatus: "meeting_booked",
        assignedTo: "Diego",
        notes: "Very engaged. Requested a demo after the webinar.",
      },
      {
        id: "att-32",
        firstName: "Lisa",
        lastName: "Tran",
        company: "Grainger",
        position: "Procurement Analyst",
        email: "l.tran@grainger.com",
        territory: "National",
        icpScore: 58,
        tier: "warm",
        outreachStatus: "contacted",
        notes: "Junior role but could be an internal champion.",
      },
      {
        id: "att-33",
        firstName: "Steven",
        lastName: "Clarke",
        company: "HD Supply",
        position: "VP Procurement",
        email: "s.clarke@hdsupply.com",
        territory: "National",
        icpScore: 89,
        tier: "hot",
        outreachStatus: "meeting_booked",
        assignedTo: "Santiago",
        notes: "Stayed after for 1-on-1 questions. Strong interest in fill rate module.",
      },
      {
        id: "att-34",
        firstName: "Natalie",
        lastName: "Dubois",
        company: "McLane Company",
        position: "Operations Manager",
        email: "n.dubois@mclaneco.com",
        territory: "National",
        icpScore: 73,
        tier: "warm",
        outreachStatus: "no_show",
        assignedTo: "Diego",
        notes: "Registered but did not attend.",
      },
    ],
    teamProgress: {
      totalAttendees: 5,
      contacted: 4,
      meetingsBooked: 2,
      noShows: 1,
      byTerritory: [
        { territory: "National", total: 5, contacted: 4, meetings: 2 },
      ],
    },
  },
];
